services:

  core-router:
    image: alpine:latest
    container_name: core-router
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    command: >
      sh -c "apk add --no-cache iptables tcpdump iptables-openrc && tail -f /dev/null"
    networks:
      clinical-net:
        ipv4_address: 10.10.10.254
      security-net:
        ipv4_address: 10.10.20.254
      management-net:
        ipv4_address: 10.10.30.254

  hbys:
    build: ./api/hbys
    container_name: hbys
    ports:
      - "8000:8000"
    networks:
      clinical-net:
        ipv4_address: 10.10.10.10

  pacs:
    build: ./api/pacs
    container_name: pacs
    ports:
      - "8001:8000"
    networks:
      clinical-net:
        ipv4_address: 10.10.10.11

  staff:
    build: ./api/staff
    container_name: staff
    ports:
      - "8002:8000"
    networks:
      management-net:
        ipv4_address: 10.10.30.10

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    networks:
      clinical-net:
        ipv4_address: 10.10.10.20

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      clinical-net:
        ipv4_address: 10.10.10.21

networks:
  clinical-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  security-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.20.0/24
  management-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.30.0/24
